# Edit this configuration to match your system. Currently every one of
# these but LD is used directly, but you might as well be complete.

DREAM_CFLAGS= -Os --fast-math -fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections -D_arch_dreamcast -D_arch_sub_pristine -Wall -s  -fno-stack-protector -fno-strict-aliasing
#-O2 --fast-math
DREAM_LDFLAGS=-ml -m4-single-only -Wl,-Ttext=0x8c010000 -nostartfiles -nostdlib  
DREAM_LIBS=-Wl,--start-group -lc -lgcc -Wl,--end-group -Wl,--gc-sections 
#-Wl,--gc-sections 
TARGET=sh-elf
CC=$(KOS_CC)
LD=$(KOS_LD)
AS=$(KOS_AS)
AR=$(KOS_AR)
OBJCOPY=$(KOS_OBJCOPY)


